# Generated by Django 4.2.11 on 2024-04-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_badge'),
        ('user', '0005_badge'),
    ]

    operations = [
    ]
